# Numpy

## installing numpy

In [1]:
!pip3 install numpy

## How to import numpy

In [2]:
import numpy

In [3]:
import numpy as np

In [8]:
import numpy as np
x=np.zeros(5,dtype='int32')

print(type(x[2]))
print(x)

<class 'numpy.int32'>
[0 0 0 0 0]


In [9]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((8,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# You can create an array with a range of elements:
np.arange(5)  #same like range

array([0, 1, 2, 3, 4])

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

In [22]:
arr=np.array([2,1,5,3,7,4,6,8])

In [23]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# 02/03/2024

# Concatanate

### np.concatenate()

In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

print(x)
print("====================")
print(y)
print("====================")
print(y.T)#t is transpose
print("====================")

# You can concatenate them with:
print(np.concatenate((x,y),axis=0))    # to get column wise give axis=0
print("====================")
print(np.concatenate((x,y.T),axis=1))  # to get row wise give axis=1

[[1 2]
 [3 4]]
[[5 6]]
[[5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [6]:
# tensor is 3D,more dimensions array or more than 2D is called tensor 

In [7]:
array_example=np.array([[[0,1,2,4,3],
                         [4,5,6,7,4]],
                        
                        [[0,1,2,3,4],
                         [4,5,6,7,5]],
                       
                        [[0,1,2,3,6],
                         [4,5,6,7,9]],
                       ])

In [8]:
print(array_example)

[[[0 1 2 4 3]
  [4 5 6 7 4]]

 [[0 1 2 3 4]
  [4 5 6 7 5]]

 [[0 1 2 3 6]
  [4 5 6 7 9]]]


In [9]:
array_example.ndim

3

In [10]:
array_example.size

30

In [11]:
array_example.shape

(3, 2, 5)

# Reshape

In [12]:
import numpy as np
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [13]:
b=a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [14]:
a=np.arange(6)
b=a.reshape(3,5)
print(b)  # here it cannot reshape in 3,5 so it shows error

ValueError: cannot reshape array of size 6 into shape (3,5)

# Resize

In [15]:
arr= np.array([1,2,3,4,5,6])
arr.resize((2,3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
arr=np.array([1,2,3,4,5,6])
arr.resize((3,4))
print(arr)  # here in resize the impossible reshaping of 3,4 can be done with resize using 0 in the veccant place.

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


# converting

#### This means that a 1D array will  become a 2D array,a 2D array will become a 3D array,and so on.

In [19]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6]
(6,)
1


In [20]:
a2=a[np.newaxis, :]
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [21]:
a3=a2[np.newaxis :]
print(a3)
print(a3.shape)
print(a3.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [23]:
col_vector=a[:,np.newaxis]
col_vector.shape
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [24]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [25]:
b=np.expand_dims(a,axis=1)
print(b.shape)
print(b.ndim)

(6, 1)
2


# Indexing and Slicing

In [26]:
# for 2D array
data=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(data)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(data[1][3])

8


In [32]:
print(data[0,1])

print(data[1:3])
print("========")

print(data[0:3,1])

2
[[ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]


In [33]:
print(data.max(axis=0))
print(data.max(axis=1))
print(data.shape)

[ 9 10 11 12]
[ 4  8 12]
(3, 4)


In [40]:
print(data[data < 5])

[1 2 3 4]


In [41]:
five_up = (data >= 5)
print(data[five_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2 = data[data % 2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
five_up = (data > 5)|(data == 5)
print(data[five_up])

[ 5  6  7  8  9 10 11 12]


#### you can also  stack two existing array,both vertically and horizontally. 

In [44]:
a1=np.array([[1,2],
             [2,2]])

a2= np.array([[3,3],
            [4,4]])

In [45]:
# you can stackthem vertically with vstack:

np.vstack((a1,a2))

array([[1, 2],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
## stack them horizontally with hstack:

np.hstack((a1,a2))

array([[1, 2, 3, 3],
       [2, 2, 4, 4]])

In [48]:
import numpy as np
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [50]:
# if you wanted to split this array into four equally shaped arrays ,you would run:
print(np.hsplit(x,4))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [16, 17, 18]]), array([[ 7,  8,  9],
       [19, 20, 21]]), array([[10, 11, 12],
       [22, 23, 24]])]


In [51]:
# if you wanted to split your array after the thrid and fifth column , you'd run:
np.hsplit(x,(3,5))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

# How to get unique items and counts

#### np.unique()

In [52]:
a = np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [53]:
unique_values,indices_list=np.unique(a,return_index=True) # to find the 1st position of the above values 

print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [54]:
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
unique_values =np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [56]:
unique_rows = np.unique(a_2d,axis=0)

print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
